update some translation
haishanh/yacd pull request #682
Opened 2022-04-04 07:35 UTC by sjtuross

2022-05-08 15:50 UTC, haishanh requested changes

2022-05-08 15:50 UTC, haishanh commented on src/i18n/zh.ts
> +  proxy_provider: '机场',
我不认为 Proxy Provider 翻译成 机场 是准确的。
1. 很多人用的是自己的服务器自建的，不一定用的是机场。
2. 这个地方的 Provider 本地指的也不是具体的 “服务”提供者，而是抽象的一组代理的集合

我也不认为翻译成诸如 代理集 是恰当的。我的选择是不如不翻。

2022-05-08 15:50 UTC, haishanh commented on src/i18n/zh.ts
> +  update_all_proxy_provider: '更新所有机场',
这两项最好也不要翻了

2022-05-08 15:51 UTC, haishanh commented
Thanks for the PR. Sorry for nitpicking. Let me know if you want to continue or not.

2022-05-08 16:04 UTC, sjtuross commented on src/i18n/zh.ts
> +  proxy_provider: '机场',
如您所说没有特别恰当的翻译，我之所以选择机场，是觉得最形象最接地气。机场代表一个集合，不特指自建还是服务提供者。另外在代理那个中文页面，Proxy Provider看起来特别突兀。

2022-05-08 16:31 UTC, sjtuross commented on src/i18n/zh.ts
> +  update_all_proxy_provider: '更新所有机场',
provider翻译成订阅如何？作为使用者其实就是subscriber，也便于理解

rule provider - 规则订阅
proxy provider - 代理订阅

2022-05-09 01:31 UTC, haishanh commented on src/i18n/zh.ts
> +  proxy_provider: '机场',
我不觉的“接地气”是重要的 🤣
要不就 proxy provider => 代理集 rule provider => 规则集，至少是准确的。

2022-05-09 01:31 UTC, haishanh commented on src/i18n/zh.ts
> +  update_all_proxy_provider: '更新所有机场',
proxy provider => 代理集 rule provider => 规则集 ?

2022-05-09 05:26 UTC, sjtuross commented on src/i18n/zh.ts
> +  update_all_proxy_provider: '更新所有机场',
个人想法：

1. proxy group叫代理组，proxy provider叫代理集，貌似准确但区分度不够
2. 正如您建议"代理集"，重点是描述内容，而不是纯粹翻译一个技术名词。provider大部分情况都是来自外部非本地链接，“订阅”突出了内容的来源，获取方式，更新机制等特征

2022-06-06 07:12 UTC, whenov commented on src/i18n/zh.ts
> +  update_all_proxy_provider: '更新所有机场',
我觉得可以直译成“供应商”或“供应者”

2023-01-30 13:54 UTC, closed without merging